name: Docs Deployment

on:
  pull_request:
    branches: [docs]
  push:
    branches: [docs]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          cd website
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Release to GitHub Pages
        env:
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: ruben.arushanyan24@gmail.com
          GIT_USER: ruben-arushanyan
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email ${{ env.GH_EMAIL }}
          git config --global user.name ${{ env.GIT_USER }}
          cd website
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy